### ISSUE TITLE
Add timestamps between stages for traceability

### ISSUE THREAD

**Issue by stefanDeveloper** [stefanDeveloper/heiDGAF#11]
## Summary
To be able to run performance analysis, we need timestamps between each stage to calculate the delta.

### Basic example
```json
{
...
  "timestamp_stages": {
    "timestamp_prefilter_in": "2024-07-02T12:52:50.988Z"
    "timestamp_prefilter_out": "2024-07-02T12:52:50.988Z"
    ...
  }
}
```

### Motivation
Performance analysis is an great indicator to see how well we perform when more data is injected into our pipeline.

**Comment by lamr02n** [comment]
I have some questions to the implementation of such an approach:

**1.  What data should the timestamps be based on?** 
If I understood this correctly, we want to measure the time span between the point in time, at which some piece of data enters a stage for the first time, and the point in time, at which that _same_ piece of data exits that stage of the pipeline. Therefore, the piece of data, for which we collect the timestamps, must be fixed. However, since the type of data packets changes throughout the pipeline, starting with single log lines and ending in filtered, analyzed packets/batches, not all pieces of data will go through the full pipeline. 
I suppose that we cannot simply store all timestamps for all log lines, since this would mean a lot of overhead. We could also store the timestamps for each batch, which would mean less overhead, but also only allow measurement of stages 3 to 5, since stages 1 and 2 work with single log lines.

**2. How would we store the data?** 
We could either have a single JSON file for storing all the timestamps or separate ones for each piece of data. We would also need to make sure, that we do not open and close files multiple times, but instead either keep them open per container and have all the timestamps for this container in one place (which we would also have to combine at some point?) or pull it through the pipeline with `marshmallow` or some own class and write the data into a file at the end. Possibly, we can also use Kafka for retrieving the timestamps (see below).

Here is **my suggestion** for an implementation: We introduce a new module that checks on a Kafka topic. Each of the existing pipeline modules produces a Kafka message under that topic including the name of the module, e.g. Prefilter, the piece of information that the timestamps refer to, e.g. some message ID, and the timestamps of entry and exit. This way, the overhead wouldn't affect the pipeline modules and we have a central module where all timestamps can be handled. However, the distinction between single log lines and batches could still lead to the necessity for interpreting the timestamps later on. We can either ignore that for now or maybe come up with something else :-)

**Comment by lamr02n** [comment]
After discussing this issue, we have come to the conclusion that it is best to store the timestamps as metadata for each batch and send it with the batch through the pipeline.

**Comment by lamr02n** [comment]
In order for this to work, we should have a field `metadata` that is sent with each batch. This will be added by #43.

**Comment by lamr02n** [comment]
Due to the new Monitoring feature, we added ClickHouse to store monitoring related data. Instead of sending the timestamps through the pipeline, we now insert them to ClickHouse.
